[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

build_flags =
    -DBLYNK_NO_BUILTIN

lib_deps =
    blynkkk/Blynk@^1.3.2
    madhephaestus/ESP32Servo@^0.12.0

monitor_speed = 115200